[workspace]

members = [
  "webserver",
  "workers/delete_directory",
  "workers/email",
  "workers/expire_paste",
]

[patch.crates-io]
syntect = { git = "https://github.com/jkcclemens/syntect", branch = "prefixes" }
