[general]
site_name = "paste"
site_domain = "paste.gg"
# Set this to include custom content on the /about page
# If not set, the About link in the navbar will not be displayed
# about_file = "about.html"

# paste can use Akismet to help stop spam. Just set an API key here and paste will do the rest.
# Leave this blank or comment it out if not using Akismet.
[spam.akismet]
api_key = ""

[store]
# The path on the filesystem where pastes will be stored.
# For production docker, this should be set to "/store"
path = "./store"

# Sender information for emails sent from the server
[email.sender]
name = ""
from = ""

# SMTP information for emails sent from the server
# paste enforces TLS without negotiation
[email.smtp]
# address for smtp
address = ""
# domain for validating cert
domain = ""
port = 0
username = ""
password = ""
